### ISSUE TITLE
React.js: Create Digital clock web app in React.js

### ISSUE THREAD

**Issue by khaymanii** [khaymanii/JSFusion#10]

**Comment by syedmaazsaeed** [comment]
I want to fix Your Issues I am A MERN Stack Developer .

**Comment by khaymanii** [comment]
Ok go ahead and fix it.
Please don't forget to leave a ⭐on the repo.

Thanks

**Comment by syedmaazsaeed** [comment]
I was busy with my university Exams what can I do now?

**Comment by khaymanii** [comment]
Oh okay.

I hope you exam went well.

You can go ahead and create a digital clock web app with React Js.

You can as well read the Contribution.md file for guidelines on how to contribute.

Don't forget to give the repo a star⭐.

Goodluck.

**Comment by syedmaazsaeed** [comment]
Okay . Thank You Soo much .

**Comment by khaymanii** [comment]
Your PR has been merged to the main repo successfully and your now a contributor to the community.

**Comment by khaymanii** [comment]
I'd love to get your Linkedin and twitter username so I can make a post with regards to this contribution you made and also i'll love you to show a little support by promoting the community to other developers to contribute.

Thanks.

**Comment by syedmaazsaeed** [comment]
Thank yOU
